version: "3.8"

services:
  auth-service:
    image: authservice
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    build: auth-service/
    restart: on-failure
    links:
      - eureka_server
      - user-service
    depends_on:
      - user-service
  user-service:
    image: userservice
#    extra_hosts:
#      - localhost:192.168.31.151
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - spring.datasource.url=jdbc:mysql://sql:3306/AIRPORT?serverTimezone=UTC
    build: user-service/
    restart: on-failure
    links:
      - eureka_server
    depends_on:
      - cloud-gateway
  cloud-gateway:
    image: cloudgateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    build: cloud-gateway
    restart: on-failure
    links:
      - eureka_server
    depends_on:
      - eureka_server
    ports:
      - "9090:8090"
  eureka_server:
    #    container_name:
    hostname: eurekaserver
    image: eurekaserver
    build: eureka-server/
    restart: on-failure
    ports:
      - "8761:8761"
  flight-service:
#    extra_hosts:
#      - localhost:192.168.31.151
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
      - spring.datasource.url=jdbc:mysql://sql:3306/AIRPORT?serverTimezone=UTC
    build: flight-service/
    restart: on-failure
    links:
      - eureka_server
  mysqldb:
    platform: linux/x86_64
    hostname: sql
    image: mysql:8.0.28
    restart: unless-stopped
    environment:
      - MYSQLDB_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=airport
      - MYSQLDB_DOCKER_PORT=3306
    volumes:
      - "./init_scripts:/docker-entrypoint-initdb.d"


