DROP TABLE IF EXIST roles;

DROP TABLE IF EXIST user;

DROP TABLE IF EXIST passport;

DROP TABLE IF EXIST passenger;

DROP TABLE IF EXIST terminal;

DROP TABLE IF EXIST gate;

DROP TABLE IF EXIST route;


DROP TABLE IF EXIST airline;

DROP TABLE IF EXIST aircraft;


DROP TABLE IF EXIST flight;

DROP TABLE IF EXIST ticket;