DROP DATABASE IF EXISTS AIRPORT;
DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS aircraft;
DROP TABLE IF EXISTS aircraft_type;
DROP TABLE IF EXISTS airline;
DROP TABLE IF EXISTS route;
DROP TABLE IF EXISTS gate;
DROP TABLE IF EXISTS terminal;
DROP TABLE IF EXISTS passenger;
DROP TABLE IF EXISTS passport;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS roles;







